In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
desired_width = 360
pd.set_option('display.width', desired_width)

from IPython.display import display, HTML
import datetime

display(HTML(data="""
<style>
    div#notebook-container    { width: 100%; }
</style>
"""))
plt.rcParams['figure.figsize'] = [16,4]

In [2]:
trainDt = pd.read_csv('kc_house_train_data2.csv')
testDt = pd.read_csv('kc_house_test_data2.csv')

len(trainDt), len(testDt)

(17384, 4229)

In [3]:
trainDt.head(10)

id             date      price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view     ...      grade  sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000   221900.0         3       1.00         1180      5650     1.0           0     0     ...          7        1180              0      1955             0    98178  47.5112 -122.257           1340        5650
1  6414100192  20141209T000000   538000.0         3       2.25         2570      7242     2.0           0     0     ...          7        2170            400      1951          1991    98125  47.7210 -122.319           1690        7639
2  5631500400  20150225T000000   180000.0         2       1.00          770     10000     1.0           0     0     ...          6         770              0      1933             0    98028  47.7379 -122.233           2720        8062
3  2487200875  20141209T000000   604000.0         4       3.00         1960      5000     1.0           0     0     ...          7        1050            910      1965             0    98136  47.5208 -122.393           1360        5000
4  1954400510  20150218T000000   510000.0         3       2.00         1680      8080     1.0           0     0     ...          8        1680              0      1987             0    98074  47.6168 -122.045           1800        7503
5  7237550310  20140512T000000  1225000.0         4       4.50         5420    101930     1.0           0     0     ...         11        3890           1530      2001             0    98053  47.6561 -122.005           4760      101930
6  1321400060  20140627T000000   257500.0         3       2.25         1715      6819     2.0           0     0     ...          7        1715              0      1995             0    98003  47.3097 -122.327           2238        6819
7  2008000270  20150115T000000   291850.0         3       1.50         1060      9711     1.0           0     0     ...          7        1060              0      1963             0    98198  47.4095 -122.315           1650        9711
8  2414600126  20150415T000000   229500.0         3       1.00         1780      7470     1.0           0     0     ...          7        1050            730      1960             0    98146  47.5123 -122.337           1780        8113
9  3793500160  20150312T000000   323000.0         3       2.50         1890      6560     2.0           0     0     ...          7        1890              0      2003             0    98038  47.3684 -122.031           2390        7570

[10 rows x 21 columns]

# Useful SFrame summary functions

In order to make use of the closed form solution as well as take advantage of sklearn built in functions we will review some important ones. In particular:
* Computing the sum of an SArray
* Computing the arithmetic average (mean) of an SArray
* multiplying SArrays by constants
* multiplying SArrays by other SArrays

# Learning a multiple regression model

Recall we can use the following code to learn a multiple regression model predicting 'price' based on the following features:
example_features = ['sqft_living', 'bedrooms', 'bathrooms'] on training data with the following code:

(Aside: We set validation_set = None to ensure that the results are always the same)

In [18]:
example_features = ['sqft_living']#, 'bedrooms', 'bathrooms']
example_model = LinearRegression()
example_model.fit(trainDt[example_features], trainDt['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
inputdt = trainDt[example_features]
t = np.matmul(inputdt,inputdt.transpose())

MemoryError: 

In [6]:
t.shape

(17384, 17384)

In [7]:
t

array([[1392410.    , 3032611.25  ,  908607.    , ..., 1805411.5   ,
        1888011.5   , 1203606.75  ],
       [3032611.25  , 6604914.0625, 1978908.25  , ..., 3932114.625 ,
        4112014.625 , 2621407.6875],
       [ 908607.    , 1978908.25  ,  592905.    , ..., 1178108.5   ,
        1232008.5   ,  785404.75  ],
       ...,
       [1805411.5   , 3932114.625 , 1178108.5   , ..., 2340915.25  ,
        2448015.25  , 1560607.875 ],
       [1888011.5   , 4112014.625 , 1232008.5   , ..., 2448015.25  ,
        2560015.25  , 1632007.875 ],
       [1203606.75  , 2621407.6875,  785404.75  , ..., 1560607.875 ,
        1632007.875 , 1040404.5625]])

In [8]:
sp.linalg.inv(t)

MemoryError: 

In [20]:
coeficents = example_model.coef_
coeficents

array([281.95883963])

# Making Predictions

In the gradient descent notebook we use numpy to do our regression. In this book we will use existing graphlab create functions to analyze multiple regressions. 

Recall that once a model is built we can use the .predict() function to find the predicted values for data we pass. For example using the example model above:

In [10]:
predcit_y = example_model.predict(trainDt[example_features])

# Compute RSS

Now that we can make predictions given the model, let's write a function to compute the RSS of the model. Complete the function below to calculate RSS given the model, data, and the outcome.

In [11]:
def get_residual_sum_of_squares(model, data, output):
    predict_dt = output - np.matmul(data, model)
    RSS = np.matmul(predict_dt, predict_dt)
    print(round(RSS,2))
    
    return(RSS)

In [12]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[1,2,3],[1,2,3]])
c = np.matmul(a,b)
c

array([ 6, 12, 18])

In [13]:
np.matmul(c,c)

504

In [14]:
RSStest = get_residual_sum_of_squares(coeficents, testDt[example_features], testDt.price)

309717338674376.94


In [15]:
print('{:.2e}'.format(RSStest))

3.10e+14


In [16]:
RSStrain = get_residual_sum_of_squares(coeficents, trainDt[example_features], trainDt.price)

1297609785388182.0


In [17]:
print('{:.2e}'.format(RSStrain))

1.30e+15


# Create some new features

Although we often think of multiple regression as including multiple different features (e.g. # of bedrooms, squarefeet, and # of bathrooms) but we can also consider transformations of existing features e.g. the log of the squarefeet or even "interaction" features such as the product of bedrooms and bathrooms.

You will use the logarithm function to create a new feature. so first you should import it from the math library.

In [ ]:
from math import log

Next create the following 4 new features as column in both TEST and TRAIN data:
* bedrooms_squared = bedrooms\*bedrooms
* bed_bath_rooms = bedrooms\*bathrooms
* log_sqft_living = log(sqft_living)
* lat_plus_long = lat + long 
As an example here's the first one:

In [ ]:
trainDt['bedrooms_squared'] = trainDt['bedrooms'].apply(lambda x: x**2)
trainDt['bed_bath_rooms'] = trainDt['bedrooms']* trainDt['bathrooms']
trainDt['log_sqft_living'] = trainDt['sqft_living'].apply(lambda x: log(x))
trainDt['lat_plus_long'] = trainDt['lat'] + trainDt['long']

testDt['bedrooms_squared'] = testDt['bedrooms'].apply(lambda x: x**2)
testDt['bed_bath_rooms'] = testDt['bedrooms']* testDt['bathrooms']
testDt['log_sqft_living'] = testDt['sqft_living'].apply(lambda x: log(x))
testDt['lat_plus_long'] = testDt['lat'] + testDt['long']


**Quiz Question: What is the mean (arithmetic average) value of your 4 new features on TEST data? (round to 2 digits)**

In [ ]:
testDt['bedrooms_squared'].mean(),testDt['bed_bath_rooms'].mean(), testDt['log_sqft_living'].mean(), testDt['lat_plus_long'].mean()

# Learning Multiple Models

Now we will learn the weights for three (nested) models for predicting house prices. The first model will have the fewest features the second model will add one more feature and the third will add a few more:
* Model 1: squarefeet, # bedrooms, # bathrooms, latitude & longitude
* Model 2: add bedrooms\*bathrooms
* Model 3: Add log squarefeet, bedrooms squared, and the (nonsensical) latitude + longitude.

In [ ]:
model_1_features = ['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long']
model_2_features = model_1_features + ['bed_bath_rooms']
model_3_features = model_2_features + ['bedrooms_squared', 'log_sqft_living', 'lat_plus_long']

In [ ]:
coeficents

In [ ]:
example_model1 = LinearRegression()
example_model1.fit(trainDt[model_1_features], trainDt['price'])
coeficents1 = example_model1.coef_
coeficents1

In [ ]:
example_model2 = LinearRegression()
example_model2.fit(trainDt[model_2_features], trainDt['price'])
coeficents2 = example_model2.coef_
coeficents2

In [ ]:
example_model3 = LinearRegression()
example_model3.fit(trainDt[model_3_features], trainDt['price'])
coeficents3 = example_model3.coef_
coeficents3

# Comparing multiple models

Now that you've learned three models and extracted the model weights we want to evaluate which model is best.

First use your functions from earlier to compute the RSS on TRAINING Data for each of the three models.

**Quiz Question: Which model (1, 2 or 3) has lowest RSS on TRAINING Data?** Is this what you expected?

Now compute the RSS on on TEST data for each of the three models.

In [ ]:
RSStrain1 = get_residual_sum_of_squares(coeficents1, trainDt[model_1_features], trainDt.price)

In [ ]:
RSStrain2 = get_residual_sum_of_squares(coeficents2, trainDt[model_2_features], trainDt.price)

In [ ]:
RSStrain3 = get_residual_sum_of_squares(coeficents3, trainDt[model_3_features], trainDt.price)

In [ ]:
RSStest1 = get_residual_sum_of_squares(coeficents1, testDt[model_1_features], testDt.price)

In [ ]:
RSStest2 = get_residual_sum_of_squares(coeficents2, testDt[model_2_features], testDt.price)

In [ ]:
RSStest3 = get_residual_sum_of_squares(coeficents3, testDt[model_3_features], testDt.price)

In [ ]:
RSStest = get_residual_sum_of_squares(coeficents, testDt[example_features], testDt.price)